pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

#Your build pipeline references an undefined variable named ‘Parameters.solution’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.solution’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references an undefined variable named ‘Parameters.ArtifactName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.8.0'
  inputs:
    versionSpec: 5.8.0

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: jaybrockway.SetAssemblyVersion.jaybrockway-SetAssemblyVersion-task.SetAssemblyVersion@2021
  displayName: 'Set Assembly Version $(Build.SourcesDirectory)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(Parameters.solution)'
    msbuildArgs: '/p:GenerateDocumentation=true /p:VisualStudioVersion=12.0 /p:DeployOnBuild=true  /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true   /p:DeployDefaultTarget=WebPublish /p:PublishProfile=IIS '
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'Test Assemblies'
  inputs:
    testAssemblyVer2: |
     **\BolaoNet.Tests.dll
     !**\*TestAdapter.dll
     !**\obj\**
     !**\BolaoNet.Tests.Debug\**
     !**\BolaoNet.MVC.Tests\**
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- powershell: |
   # Write your PowerShell commands here.
   
   Get-ChildItem -Path '$(Build.SourcesDirectory)' -recurse
   # Get-ChildItem -Path '$(Build.SourcesDirectory)' -recurse
  displayName: 'PowerShell Script'

- script: |
   echo del "$(Build.SourcesDirectory)\deploy\MVC\web.config"
   del "$(Build.SourcesDirectory)\deploy\MVC\web.config"
   
   echo copy "$(Build.SourcesDirectory)\deploy\MVC\web.devops.config" "$(Build.SourcesDirectory)\deploy\MVC\web.config"
   copy "$(Build.SourcesDirectory)\deploy\MVC\web.devops.config" "$(Build.SourcesDirectory)\deploy\MVC\web.config"
    
   echo del "$(Build.SourcesDirectory)\deploy\MVC\web.devops.config"
   del "$(Build.SourcesDirectory)\deploy\MVC\web.devops.config"
   
   
  displayName: 'Rename Web.config from MVC and WebApi'

- task: CopyFiles@2
  displayName: 'Copy DacPac'
  inputs:
    SourceFolder: 'BolaoNet.Database.SqlServer\bin\release'
    Contents: |
     *.dacpac
     *.sql
    TargetFolder: '$(build.artifactstagingdirectory)\deploy'

- task: ArchiveFiles@2
  displayName: 'Archive Web MVC Files'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/deploy/MVC'
    includeRootFolder: false
    archiveFile: '$(build.artifactstagingdirectory)\deploy/zip/Mvc_$(Build.BuildNumber).zip'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(Parameters.ArtifactName)'
