
:r ..\build\0001.Cleaning_Up.sql
--:r ..\build\0051.Insert_Table_lg_content_types.sql
--:r ..\build\0052.Insert_Table_lg_log_level_types.sql
:r ..\build\0054.Insert_Table_CriteriosFixos.sql
:r ..\build\0055.Insert_Table_UserMaritalStatus.sql
:r ..\build\0056.Insert_Table_Users.sql
:r ..\build\0057.Insert_PagamentoTipo.sql
:r ..\build\0058.Insert_Table_Roles.sql
:r ..\build\0059.Insert_Table_UsersInRoles.sql
:r ..\build\0060.Insert_Table_BoloesRequestsStatus.sql
--:r ..\build\0067.Insert_Result_Premiacao.sql
:r ..\build\0098.Create_StoredProcedure_sp_JogosUsuarios_Calcule_Grupo_Melhor.sql
:r ..\build\0099.Create_StoredProcedure_sp_Jogos_Calcule_Grupo_Melhores.sql
:r ..\build\0100.Create_StoredProcedure_sp_JogosUsuarios_Calcule_Grupo.sql
:r ..\build\0101.Create_StoredProcedure_sp_JogosUsuarios_Calcule_Time.sql
:r ..\build\0102.Create_StoredProcedure_sp_JogosUsuarios_Calcule_Dependencia.sql
:r ..\build\0103.Create_StoredProcedure_sp_JogosUsuarios_Calcule_Final.sql
:r ..\build\0104.Create_StoredProcedure_sp_ProcessAposta.sql
:r ..\build\0105.Create_StoredProcedure_sp_Jogos_Calcule_Grupo.sql
:r ..\build\0106.Create_StoredProcedure_sp_Jogos_Calcule_Dependencia.sql
:r ..\build\0107.Create_StoredProcedure_sp_BoloesMembrosPontosRodadas_Organize.sql
:r ..\build\0108.Create_StoredProcedure_sp_Boloes_BuscaCriteriosPontos.sql
:r ..\build\0109.Create_StoredProcedure_sp_JogosUsuarios_CalculaPontos.sql
:r ..\build\0110.Create_StoredProcedure_sp_JogosUsuariosValidacao.sql
:r ..\build\0111.Create_StoredProcedure_sp_CampeonatosClassificacao_LoadRodada.sql
:r ..\build\0112.Create_StoredProcedure_sp_CampeonatosClassificacao_Organize.sql
:r ..\build\0114.Create_StoredProcedure_sp_Jogos_ResultInsert.sql
:r ..\build\0115.Create_StoredProcedure_sp_Boloes_Iniciar.sql
:r ..\build\0116.Create_StoredProcedure_sp_Boloes_Aguardar.sql
:r ..\build\0117.Create_StoredProcedure_sp_ApostasExtras_InsertResult.sql
:r ..\build\0118.Create_StoredProcedure_sp_Jogos_LoadJogos.sql
:r ..\build\0119.Create_StoredProcedure_sp_Jogos_LoadLastFinishedJogos.sql
:r ..\build\0120.Create_StoredProcedure_sp_Jogos_LoadNextJogos.sql
:r ..\build\0121.Create_StoredProcedure_sp_JogosUsuarios_ApostasAutomatica.sql
:r ..\build\0122.Create_StoredProcedure_sp_CampeonatosClassificacao_LoadClassificacao.sql
:r ..\build\0123.Create_Stored_Procedure_sp_Users_Load_Boloes.sql
:r ..\build\0124.Create_Stored_Procedure_sp_Users_Load_Pagamentos.sql
:r ..\build\0125.Create_Stored_Procedure_sp_BoloesMembros_LoadStatus.sql
:r ..\build\0126.Create_Stored_Procedure_sp_BoloesMembros_Del.sql
:r ..\build\0127.Create_Stored_Procedure_sp_JogosUsuarios_Load_Acertos_Dificeis.sql
:r ..\build\0128.Create_Stored_Procedure_sp_JogosUsuarios_Load_Sem_Acertos.sql
:r ..\build\0129.Create_Stored_Procedure_sp_Campeonatos_Reiniciar.sql
:r ..\build\0130.Create_Stored_Procedure_sp_Clear_Database.sql
:r ..\build\0131.Create_Stored_Procedure_sp_CampeonatosRecordTimeRecordJogosGols.sql
:r ..\build\0132.Create_Stored_Procedure_sp_CampeonatosRecordTimeRecordSemGanhar.sql
:r ..\build\0133.Create_Stored_Procedure_sp_CampeonatosRecordTimeRecordSemPerder.sql
:r ..\build\0134.Create_Stored_Procedure_sp_CampeonatosRecordTimeRecordSeqDerrotas.sql
:r ..\build\0135.Create_Stored_Procedure_sp_CampeonatosRecordTimeRecordSeqEmpates.sql
:r ..\build\0136.Create_Stored_Procedure_sp_CampeonatosRecordTimeRecordSeqVitorias.sql
:r ..\build\0137.Create_Stored_Procedure_sp_CampeonatosRecords.sql
:r ..\build\0138.Create_Stored_Procedure_sp_CampeonatosRecordGols.sql
:r ..\build\0139.Create_Stored_Procedure_sp_CampeonatosRecordGolsFrequencia.sql
:r ..\build\0140.Create_Stored_Procedure_sp_JogosUsuarios_CorrecaoEliminatorias.sql
--:r ..\build\0141.Insert_Result_Copa_2018.sql
