name: CI BolaoNet

on:
  push:
    branches:
      - master

env:
  SOLUTION: 'BolaoNet.sln'
  BUILD_CONFIGURATION: Release 
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # RESTORE (MODERNO)
      # =========================
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION }}

      # =========================
      # BUILD
      # =========================
      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      # =========================
      # TEST
      # =========================
      - name: Test
        run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build

      # =========================
      # SET VERSION  
      # =========================
      - name: Set Assembly Version
        shell: pwsh
        run: |
          $version = "2.$(Get-Date -Format yy.MM.dd)$env:GITHUB_RUN_NUMBER"
          Write-Host "Version: $version"

          Get-ChildItem -Recurse -Filter AssemblyInfo.cs | ForEach-Object {
            (Get-Content $_.FullName) `
              -replace 'AssemblyVersion\(".*"\)', "AssemblyVersion(`"$version`")" `
              -replace 'AssemblyFileVersion\(".*"\)', "AssemblyFileVersion(`"$version`")" |
              Set-Content $_.FullName
          }

      # =========================
      # PUBLISH  
      # =========================
      - name: Publish MVC
        run: dotnet publish -c ${{ env.BUILD_CONFIGURATION }} -o publish

      # =========================
      # DACPAC COPY  
      # =========================
      - name: Copy DacPac
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path deploy | Out-Null
          Copy-Item "${{ github.workspace }}\BolaoNet.Database.SqlServer\bin\Release\*.dacpac" deploy -Force

      # =========================
      # TEMPLATES
      # =========================
      - name: Copy Templates
        shell: pwsh
        run: |
          Copy-Item "${{ github.workspace }}\BolaoNet.Infra.Notification.Mail\TemplatesHtml\*" `
            -Destination "${{ github.workspace }}\deploy\MVC\TemplatesHtml" `
            -Recurse -Force

      # =========================
      # ZIP
      # =========================
      - name: Create ZIP
        shell: pwsh
        run: |
          $buildNumber = "2.$(Get-Date -Format yy.MM.dd)$env:GITHUB_RUN_NUMBER"
          New-Item -ItemType Directory -Force -Path deploy/zip | Out-Null

          Compress-Archive `
            -Path "${{ github.workspace }}/publish/*" `
            -DestinationPath "deploy/zip/Mvc_$buildNumber.zip"

          echo "BUILD_NUMBER=$buildNumber" >> $env:GITHUB_ENV

      # =========================
      # ARTIFACT
      # =========================
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: deploy

          
# # =========================
# # DEPLOY - SOMEE
# # =========================
#   deploy-somee:
#     needs: build
#     runs-on: windows-latest
#     environment: dev-somee

#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: drop

#       - name: Extract files
#         run: |
#           Expand-Archive -Path drop/app.zip -DestinationPath extracted

#       #- name: Extract files
#       #  run: |
#       #    powershell Expand-Archive -Path app.zip -DestinationPath extracted

#       - name: Replace tokens in config
#         shell: pwsh
#         run: |
#           $files = Get-ChildItem -Path extracted -Recurse -Include *.config
#           foreach ($file in $files) {
#             (Get-Content $file.FullName) `
#               -replace '_#DB_SERVER#_', '${{ secrets.DB_SERVER }}' `
#               -replace '_#DB_NAME#_', '${{ secrets.DB_NAME }}' `
#               -replace '_#DB_USER#_', '${{ secrets.DB_USER }}' `
#               -replace '_#DB_PASSWORD#_', '${{ secrets.DB_PASSWORD }}' `
#               | Set-Content $file.FullName
#           }

#       - name: Install SqlPackage
#         run: choco install sqlpackage

#       - name: Deploy Database
#         run: |
#           sqlpackage /Action:Publish `
#           /SourceFile:"./BolaoNet.Database.SqlServer.dacpac" `
#           /TargetConnectionString:"Server=${{ secrets.DB_SERVER }};Database=${{ secrets.DB_NAME }};User Id=${{ secrets.DB_USER }};Password=${{ secrets.DB_PASSWORD }};TrustServerCertificate=True" `
#           /p:BlockOnPossibleDataLoss=false

#       - name: FTP Deploy
#         uses: SamKirkland/FTP-Deploy-Action@latest
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local-dir: extracted/
#           server-dir: /www.bolaonet.somee.com/