name: CI BolaoNet

on:
  push:
    branches:
      - master

env:
  SOLUTION: 'BolaoNet.sln'
  PROJECT_DEPLOY: 'BolaoNet.MVC\BolaoNet.MVC.csproj'
  BUILD_CONFIGURATION: Release 
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # RESTORE
      # =========================
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: nuget restore ${{ env.SOLUTION }} 

      # =========================
      # BUILD
      # ========================= 
      - name: Build solution
        run: msbuild ${{ env.SOLUTION }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform="Any CPU"

      # =========================
      # TEST
      # =========================
      - name: Test
        run: msbuild ${{ env.SOLUTION }} /p:RunTests=true

      # =========================
      # SET VERSION  
      # =========================
      - name: Set Assembly Version
        shell: pwsh
        run: |
          $version = "2.$(Get-Date -Format yy.MM.dd)$env:GITHUB_RUN_NUMBER"
          Write-Host "Version: $version"

          Get-ChildItem -Recurse -Filter AssemblyInfo.cs | ForEach-Object {
            (Get-Content $_.FullName) `
              -replace 'AssemblyVersion\(".*"\)', "AssemblyVersion(`"$version`")" `
              -replace 'AssemblyFileVersion\(".*"\)', "AssemblyFileVersion(`"$version`")" |
              Set-Content $_.FullName
          }

      # =========================
      # PUBLISH  
      # ========================= 
      - name: Build MVC
        run: msbuild ${{ env.PROJECT_DEPLOY }} /p:GenerateDocumentation=true /p:DeployOnBuild=true  /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DeployDefaultTarget=WebPublish /p:PublishProfile=IIS 

      # =========================
      # DACPAC COPY  
      # ========================= 
      - name: Copy DacPac
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path deploy | Out-Null

          $files = Copy-Item "${{ github.workspace }}\BolaoNet.Database.SqlServer\bin\Release\*.dacpac" deploy -Force -PassThru

          Write-Host "Arquivos copiados: $($files.Count)"

      # =========================
      # TEMPLATES
      # =========================
      - name: Copy TemplatesHtml
        shell: pwsh
        run: |
        
          $source = "${{ github.workspace }}\BolaoNet.Infra.Notification.Mail\TemplatesHtml"
          $dest = "${{ github.workspace }}\deploy\MVC\TemplatesHtml"

          New-Item -ItemType Directory -Force -Path $dest | Out-Null

          $files = Get-ChildItem -Path $source -Recurse

          Write-Host "Arquivos encontrados: $($files.Count)"

          Copy-Item "$source\*" -Destination $dest -Recurse -Force

          Write-Host "Copy finalizado"

      # =========================
      # AJUSTES DE WEBCONFIG E LOG
      # =========================
      - name: Replace Web.config (robusto)
        shell: pwsh
        run: |
          $path = "${{ github.workspace }}\deploy\MVC"

          if (!(Test-Path $path)) {
            $path = "${{ github.workspace }}\BolaoNet.MVC\obj\Release\Package\PackageTmp"
            Write-Host "Fallback path: $path"
          }

          $webConfig = "$path\web.config"
          $devopsConfig = "$path\web.devops.config"

          if (Test-Path $devopsConfig) {

            if (Test-Path $webConfig) {
              Remove-Item $webConfig -Force
            }

            Copy-Item $devopsConfig $webConfig -Force
            Remove-Item $devopsConfig -Force

            Write-Host "Config substituído com sucesso"

          } else {
            Write-Host "web.devops.config não encontrado"
          }

      # =========================
      # ZIP
      # ========================= 
      - name: Ensure publish folder exists
        shell: pwsh
        run: |
          if (!(Test-Path "${{ github.workspace }}\deploy\MVC")) {
            New-Item -ItemType Directory -Force -Path "${{ github.workspace }}\deploy\MVC"
          }

      - name: Debug publish folder
        shell: pwsh
        run: |
          Write-Host "=== SEARCH publish FILES ==="

          Get-ChildItem "${{ github.workspace }}" -Recurse -File |
            Where-Object { $_.FullName -like "*publish*" } |
            Select-Object FullName

          Write-Host "=== DIRECT publish CONTENT ==="

          Get-ChildItem "${{ github.workspace }}\publish" -Recurse -Force -ErrorAction SilentlyContinue |
            Select FullName


      - name: Create ZIP
        shell: pwsh
        run: |
          $buildNumber = "2.$(Get-Date -Format yy.MM.dd)$env:GITHUB_RUN_NUMBER"

          $source = "${{ github.workspace }}\deploy\MVC"

          Write-Host "Checking: $source"

          if (!(Test-Path $source)) {
            Write-Host "FALLBACK: trying PackageTmp"

            $source = "${{ github.workspace }}\BolaoNet.MVC\obj\Release\Package\PackageTmp"

            if (!(Test-Path $source)) {
              throw "Nenhum output de publish encontrado"
            }
          }

          New-Item -ItemType Directory -Force -Path deploy/zip | Out-Null

          Compress-Archive -Path "$source\*" -DestinationPath "deploy/zip/Mvc_$buildNumber.zip"

          echo "BUILD_NUMBER=$buildNumber" >> $env:GITHUB_ENV

          Write-Host "ZIP criado com sucesso"
 
      # =========================
      # ARTIFACT
      # =========================
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: deploy

          
# =========================
# DEPLOY - SOMEE
# =========================
  deploy-somee:
    needs: build
    runs-on: windows-latest
    environment: Somee - PROD

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: drop

      # - name: Extract files
      #   run: |
      #     Expand-Archive -Path drop/app.zip -DestinationPath extracted

      - name: Extract files
        shell: pwsh
        run: |
          $zip = Get-ChildItem -Path . -Recurse -Filter "*.zip" | Select-Object -First 1

          if (!$zip) {
            throw "ZIP não encontrado"
          }

          Write-Host "ZIP encontrado: $($zip.FullName)"

          Expand-Archive -Path $zip.FullName -DestinationPath extracted -Force


      - name: Replace tokens in config
        shell: pwsh
        run: |
          $files = Get-ChildItem -Path extracted -Recurse -Include *.config
          foreach ($file in $files) {
            (Get-Content $file.FullName) `
              -replace '_#DB_SERVER#_', '${{ secrets.DB_SERVER }}' `
              -replace '_#DB_NAME#_', '${{ secrets.DB_NAME }}' `
              -replace '_#DB_USER#_', '${{ secrets.DB_USER }}' `
              -replace '_#DB_PASSWORD#_', '${{ secrets.DB_PASSWORD }}' `
              | Set-Content $file.FullName
          }

      - name: Install SqlPackage
        run: choco install sqlpackage


      - name: Locate DacPac
        id: dacpac
        shell: pwsh
        run: |
          $dacpac = Get-ChildItem -Path . -Recurse -Filter "*.dacpac" | Select-Object -First 1

          if (!$dacpac) {
            throw "DACPAC não encontrado"
          }

          echo "path=$($dacpac.FullName)" >> $env:GITHUB_OUTPUT

      # - name: Deploy Database
      #   run: |
      #     sqlpackage /Action:Publish `
      #     /SourceFile:"./BolaoNet.Database.SqlServer.dacpac" `
      #     /TargetConnectionString:"Server=${{ secrets.DB_SERVER }};Database=${{ secrets.DB_NAME }};User Id=${{ secrets.DB_USER }};Password=${{ secrets.DB_PASSWORD }};TrustServerCertificate=True" `
      #     /p:BlockOnPossibleDataLoss=false

      - name: Deploy Database
        run: |
          sqlpackage /Action:Publish `
          /SourceFile:"${{ steps.dacpac.outputs.path }}" `
          /TargetConnectionString:"Server=${{ secrets.DB_SERVER }};Database=${{ secrets.DB_NAME }};User Id=${{ secrets.DB_USER }};Password=${{ secrets.DB_PASSWORD }};TrustServerCertificate=True" `
          /p:BlockOnPossibleDataLoss=false


      # - name: FTP Deploy
      #   uses: SamKirkland/FTP-Deploy-Action@latest
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: extracted/
      #     server-dir: /www.bolaonet.somee.com/

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: extracted/
          server-dir: /www.bolaonet.somee.com/